# Generated by Django 6.0.5 on 2026-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
