# Generated by Django 6.0.5 on 2026-05-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_momo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momo',
            name='Category',
        ),
        migrations.AddField(
            model_name='momo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
